version: 2

sources:
  - name: chat_raw
    database: chat_db
    schema: chat_raw
    tables:

      - name: chats_raw
        description: >
          Chat sessions between a customer support agent and a customer.
          Timestamps are recorded in UTC.
          A sample of ~50,000 chats has been provided
          The sample has been selected randomly over an approx. four-month timeframe.
        columns:
          - name: id
            type: string # UUID
            tests:
              - not_null
          - name: chat_category_id
            type: string # UUID, relationship with categories.id
          - name: created_at
            type: timestamp
          - name: is_customer_initiated
            type: boolean
          - name: resolved_at
            type: timestamp

      - name: categories_raw
        description: >
          Categories denoting the topic of conversation in a chat.
          Categories are hierarchical, with root nodes having a null parent_id.
          Categories can be disabled, if a chat has a disabled category then it should be treated as having no category.
        columns:
          - name: id
            type: string # UUID
            tests:
              - not_null
          - name: parent_id
            type: string # UUID, relationship with categories.id
          - name: disabled
            type: boolean